# 无Redis环境配置 - 简化学习环境
# 适合不想安装Redis的Windows学习者

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: no-redis
  
  # 数据库配置
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_ecommerce_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # 禁用Redis
  data:
    redis:
      repositories:
        enabled: false

# 使用内存缓存替代Redis
cache:
  type: simple  # 使用Spring的简单内存缓存
  
# JWT配置
jwt:
  secret: ai-ecommerce-no-redis-dev-secret-key-2024
  expiration: 86400000

# 日志配置
logging:
  level:
    com.aicommerce: DEBUG
    org.springframework.security: DEBUG
  file:
    name: C:/temp/ai-ecommerce/logs/application.log